---
title: "Research"
---

## Working Papers

- [**Peer effects in voluntary environmental programs: An application to urban water quality**](assets/papers/brent_et_al_peer_effects_gsi.pdf) (with Douglas Wrenn; Gabe Lara; Joe Cook - Accepted *Journal of the Association of Environmental and Resource Economists*)
<details class="wp-abstract">
<summary>Abstract</summary>
Stormwater runoff is a growing source of urban water pollution, costing cities billions of dollars. We investigate peer effects in a voluntary residential green stormwater infrastructure program that mitigates stormwater runoff. Our identification strategy exploits households’ relative position in eligible sewersheds that generates plausibly exogenous variation in eligible peers. Peer adoption causes a 0.2% increase in the annual adoption probability, a 66% increase relative to the mean. According to our calculations, the policy reduced compliance costs by $85–235 million for the Seattle metropolitan area, of which roughly 40% is due to peer effects.
</details>


- [**Conservation and distributional consequences of pricing scarce water during droughts**](https://www.rff.org/publications/working-papers/conservation-and-distributional-consequences-of-pricing-scarce-water-during-droughts/)  (with Derek Wietelman; Casey Wichman - Revise & Resubmit *Journal of the Association of Environmental and Resource Economists*) 
<details class="wp-abstract">
<summary>Abstract</summary>
Using price incentives to allocate scarce resources is a core tenet of economics but may result in unpalatable distributional outcomes. We analyze the efficacy of prices as a means of inducing water conservation during severe drought by studying the introduction of surcharges enacted within existing nonlinear rate structures. Embedding machine learning counterfactual prediction methods within a demand framework to isolate exogenous price variation, we find evidence that households exhibit a significant demand response despite the temporary nature of surcharges. However, further investigation reveals that surcharges alone cannot explain a majority of the conservation observed despite steep price increases. “Budget-based” rates undercut scarcity signals by shielding large users from binding price increases, and surcharges themselves do little to reduce the regressivity of water expenditures. Simpler rate structures can dominate along equity dimensions, and their progressivity can be enhanced via lump-sum transfers within the rate structure.
</details>


- [**Do behavioral nudges interact with prevailing economic incentives? Evidence from water consumption**](https://www.rff.org/publications/working-papers/do-behavioral-nudges-interact-with-prevailing-economic-incentives-pairing-experimental-and-quasi-experimental-evidence-from-water-consumption/) (with Casey Wichman)
<details class="wp-abstract">
<summary>Abstract</summary>
Behavioral nudges are popular instruments to promote prosocial behavior, particularly in settings with unpriced externalities. Nudges may interact with existing incentives, however, by crowding out intrinsic motivation to conserve or by increasing price salience. We investigate the interaction of prices and nudges for water conservation in two experiments in neighboring utilities. First, we layer randomized behavioral treatments on top of price variation driven by lot-size thresholds that exogenously assign marginal prices. Second, we explore whether behavioral treatments affect consumers’ price elasticities. Our findings suggest that nudges do not induce more conservation at higher prices, nor do they increase price sensitivity.
</details>


- [**Consumer value of information and the behavioral response to carbon and calorie food labels**](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5615750) (with Amit Sharma; Dahlia Durun Barruah)  
<details class="wp-abstract">
<summary>Abstract</summary>
The food system accounts for up to a third of global emissions, with carbon footprints varying greatly by food type. Despite this, carbon footprint labels are not required on restaurant menus, unlike calorie labels for large U.S. chains, and voluntary adoption is not common. This study examines consumer willingness to pay for carbon and calorie labels and their joint effect on food choices through a randomized field experiment (N=313) at a university restaurant. Participants received either a standard or augmented menu with calorie and carbon information, with one treatment arm randomizing the price for accessing this information. The augmented menu reduced beef consumption by 15%, primarily shifting choices to chicken. Among those actively choosing the information, beef consumption decreased by over 33%. Consumers valued the labels at 11% of the meal cost. These findings highlight demand for environmental transparency and its potential to shift consumer behavior toward lower-carbon food choices.
</details>


- **Adopting solar power for irrigation: Implications for groundwater depletion in Gujarat** (with Praharsh Patel; Emily Pakhtigian; Christopher Scott - email for a copy)  
<details class="wp-abstract">
<summary>Abstract</summary>
Groundwater is a vital resource for irrigation in India supporting food security and rural livelihoods. Energy subsidies for groundwater pumping improve short-term water access but worsen over-extraction incentives, accelerating depletion of this already overused common pool resource. Economic theory supports pricing or taxing groundwater, but even removing subsidies is politically difficult. Grid-connected solar irrigation offers a potential solution by creating an incentive to conserve groundwater from selling unused energy back to the grid. This study evaluates the impact of grid-connected solar irrigation under the Suryashakti
Kisan Yojna (SKY) policy through a survey of 2,798 farmers. Our findings indicate that major implementation challenges limit the ability of solar irrigation to incentivize groundwater conservation. These findings highlight the importance of policy implementation to meet policy
objectives.

</details>


- [**Financial literacy and academic outcomes**](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4078004) (with Douglas Wrenn)  
<details class="wp-abstract">
<summary>Abstract</summary>
Outstanding student debt has almost doubled in the past decade to over \$1.7 trillion. Delayed graduation contributes to the student debt burden by increasing tuition payments without any additional wage premium. Behavioral theory suggests that young adults are prone to biases limiting their ability to connect short-run actions with long-run outcomes. We attempt to correct these biases using a low-touch financial literacy intervention within a randomized encouragement design at a large public university. We randomly invite and incentivize first-year students to participate in an online tutorial connecting short-run academic success to long-run debt obligations and examine differences in academic outcomes. The intervention increases credits earned and GPA: treated students earn 0.55 more credits per semester and GPAs increase by 0.08. We also find substantially larger effects for underrepresented minorities and less-prepared students. The intervention puts these at-risk students on track to graduate on time, where they would otherwise fall behind. Applying a simply benefit-cost formula, our results suggest that spending one dollar incentivizing financial literacy in this context leads to tuition savings of \$115.
</details>

- **Behavioral responses to two-part tariffs: Evidence from the introduction of volumetric water pricing** (with Praharsh Patel and Casey Wichman - email for a copy)  
<details class="wp-abstract">
<summary>Abstract</summary>
Economists often advocate for pricing mechanisms based on marginal prices to promote efficient water usage. However, consumers may find it difficult to interpret complex water pricing structures, such as nonlinear two-part tariffs that serve multiple policy objectives. In this study, we examine consumer behavior following the introduction of volumetric pricing in Sacramento, California. Our analysis reveals that volumetric pricing reduces average water consumption by 5%, although there is considerable variation among consumer groups. Low consumption households, whose bills decreased under the new pricing structure, increased their water usage by 4% despite facing increases in marginal price. 
</details>


## Published Articles

{{< include publications.qmd >}}

## Work in Progress

- **Estimating water demand at the intensive and extensive margins**

- **Flood risk perceptions, information, and the demand for adaptation**  
  (with Ishani Palandurkar)

- **Experimental evidence on the voluntary adoption and demand response to time-varying electricity rates**  
  (with Andrea La Nauze; Nathan Eisner; Casey Wichman)

- **Valuing clean water from abandoned mine reclamation**  
  (with Ishani Palandurkar)

---

## Reports & Other Publications

- Cook, J., & Brent, D. A. (2021).  
  **Do households respond to marginal or average price of piped water services?**  
  *Oxford Research Encyclopedia of Global Public Health.*  
  [Publication link](https://oxfordre.com/publichealth/view/10.1093/acrefore/9780190632366.001.0001/acrefore-9780190632366-e-189)

- Brent, D. A. (2015).  
  **Review of *Living with Water Scarcity* by David Zetland.**  
  *Water Economics and Policy*, 01, 158003 (4 pages).  
  [DOI](https://doi.org/10.1142/S2382624X158003X)

- Brent, D. A., Leibbrandt, A., & Smith, L. (2014).  
  **Economic incentives for managing peak electricity demand: Review, options, and context analysis.**  
  Melbourne, Australia, pp. 1–38.

- Yoder, J., Adam, J., Brady, M., Cook, J., Katz, S., Brent, D., Johnston, S., Malek, K., McMilan, J., & Yang, Q. (2014).  
  **Benefit–cost analysis of the Yakima Basin Integrated Plan projects.**  
  December, pp. 1–196.
